---
name: default
title: Stagen Default Theme
author:
  name: Denis Vidog
  email: github@doubleds.ru
  website: https://den4k.space
default_layout: base
imports:
  imports:
    - name: main
includes:
  head:
    - name: head
  head_after:
    - name: head_after
#  nav:
#    - name: nav
#  body_after:
#    - name: body_after
#  footer:
#    - name: footer
extras:
  preconnect_links:
    - url: https://fonts.googleapis.com
    - url: https://fonts.gstatic.com
      options:
        crossorigin: true
  css:
    - url: https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap
    - url: /css/theme.default.css
variables:
  pagefind_ignore: false
  no_title: false
