logger:
  level: debug
  format: text
  colors: true
  timestamp: true
  stacktrace: false
  stacktrace_errors: true

stagen:
  http:
    host: 127.0.0.1
    port: 8001

site:
  name: My Stagen Website
  copyright:
    title: Stagen Developers
    year: 2025
    rights: All rights reserved.
  extensions:
    - name: images
    - name: videos
    - name: markup
  agg_dicts:
    - name: tags
      keys: [tags]
  generators:
    - name: tags
      source:
        type: agg_dict
        name: tags
      template:
        name: tag
      output:
        dir: tags
        filename_template: '{{.AggDictValue}}.html'
    - name: countries
      source:
        type: database
        name: countries
      template:
        name: country
      output:
        dir: countries
    - name: rss.xml
      source:
        type: data
      template:
        name: rss.xml
      output: ~
      data:
        - id: rss
