logger:
  level: debug
  format: text
  colors: true
  timestamp: true
  stacktrace: false
  stacktrace_errors: true

stagen:
  work_dir: ./example

site:
  name: My Stagen Website
  copyright:
    title: Stagen Developers
    year: 2025
    rights: All rights reserved.
  extensions:
    - name: images
    - name: videos
    - name: markup
    - name: rss # @todo
  agg_dicts:
    - name: title
      keys: [title]
    - name: tags
      keys: [tags]
  generators:
    - name: tags
      source:
        type: agg_dict
        name: tags
      template:
        name: tag
      output:
        dir: tags
